name: Pull Request

on:
  push

permissions:
  contents: write

env:
  NODE_VERSION: 18.16.0

jobs:
  
  deploy:
    name: Build And Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout️
        uses: actions/checkout@v3

      - name: Setup Continuous integration
        uses: ./.github/actions/ci-setup

      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build
        run: npm run build

      - name: Delete env file
        run: rm .env

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
